version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vimeo/psalm
    versions:
    - 4.4.1
    - 4.5.0
    - 4.5.1
    - 4.5.2
    - 4.6.0
    - 4.6.1
    - 4.6.2
    - 4.6.3
    - 4.6.4
    - 4.7.0
